### ISSUE TITLE
Module Problem 

### ISSUE THREAD

**Issue by omkarawasthi** [architsangal/Android-App-Flight-Booking-System#1]
When I run the app is shows "no module" error =. So, can you tell how to add module in your project and from where.

**Comment by architsangal** [comment]
Hello,

You may refer to [this](https://developer.android.com/studio/projects/add-app-module).  It looks like a setup problem with the android studio; therefore, I am closing this issue. If the above link is not helpful, feel free to reopen this issue. Also, please elaborate on the issue.

**Comment by omkarawasthi** [comment]
Thank for help issue has been resolved.

**Comment by omkarawasthi** [comment]
how I connect my firebase storage to your app
